package ATFUnify where

-- Check that we can successfully unify unreduced type function types,
-- by introducing constraints.

class Container f e | f -> e where
  type Elem f = e
  wrap   :: e -> f
  unwrap :: f -> e

data Box a = Box a

instance Container (Box a) a where
  wrap = Box
  unwrap (Box x) = x

conv1 :: (Container a e) => a -> Box e
conv1 x =
  let y = unwrap x
  in wrap y

conv2 :: (Container a e) => a -> Box e
conv2 x = wrap $ unwrap x
