// A module with many rules, none of which share any state.  The
// scheduler's rule-pair work (conflict maps, disjointness testing,
// derived sequencing/urgency graphs, the Esposito blocker scan, and
// the arbitrary-choice warning scans) should scale with the number of
// *interacting* rule pairs -- here zero -- not with all pairs of rules.
//
// State is a replicated Vector and the rules are generated by an
// elaboration loop so that the source stays constant-size (the
// typechecker's cost is independent of the rule count) and the
// scheduler still sees each rule as a distinct entity.
import Vector::*;

(* synthesize *)
module mkSparseRules(Empty);
  Vector#(8192, Reg#(UInt#(16))) rs <- replicateM(mkReg(0));
  for (Integer i = 0; i < 8192; i = i + 1)
    rule incr;
      rs[i] <= rs[i] + 1;
    endrule
endmodule
