## Automatically generated by bluetcl -exec makedepend -- Do NOT EDIT
## Date: Thu Dec 19 11:17:07 AM PST 2024
## Command: bluetcl -exec makedepend -bdir $(BUILDDIR) *.bs*

$(BUILDDIR)/ActionSeq.bo:	ActionSeq.bs $(BUILDDIR)/List.bo $(BUILDDIR)/Vector.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Array.bo:	Array.bsv $(BUILDDIR)/List.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Assert.bo:	Assert.bs $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/CShow.bo:	CShow.bs $(BUILDDIR)/ListN.bo $(BUILDDIR)/Vector.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Clocks.bo:	Clocks.bsv $(BUILDDIR)/List.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/ConfigReg.bo:	ConfigReg.bs $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Connectable.bo:	Connectable.bs $(BUILDDIR)/Vector.bo $(BUILDDIR)/ListN.bo $(BUILDDIR)/Inout.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Counter.bo:	Counter.bs $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Enum.bo:	Enum.bs $(BUILDDIR)/List.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Environment.bo:	Environment.bs $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/FIFO.bo:	FIFO.bs $(BUILDDIR)/FIFOF_.bo $(BUILDDIR)/FIFOF.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/FIFOF.bo:	FIFOF.bs $(BUILDDIR)/FIFOF_.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/FIFOF_.bo:	FIFOF_.bsv $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/FIFOLevel.bo:	FIFOLevel.bsv $(BUILDDIR)/FIFOF_.bo $(BUILDDIR)/GetPut.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/FShow.bo:	FShow.bsv $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/FoldFIFO.bo:	FoldFIFO.bs $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/FoldFIFOF.bo:	FoldFIFOF.bs $(BUILDDIR)/FIFOF.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Fork.bo:	Fork.bs $(BUILDDIR)/Vector.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/GetPut.bo:	GetPut.bs $(BUILDDIR)/FIFO.bo $(BUILDDIR)/FIFOF.bo $(BUILDDIR)/Connectable.bo $(BUILDDIR)/Clocks.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Inout.bo:	Inout.bsv $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/LevelFIFO.bo:	LevelFIFO.bsv $(BUILDDIR)/FIFOLevel.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/List.bo:	List.bs $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/ListN.bo:	ListN.bs $(BUILDDIR)/List.bo $(BUILDDIR)/Vector.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Once.bo:	Once.bs $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Prelude.bo:	Prelude.bs
$(BUILDDIR)/PreludeBSV.bo:	PreludeBSV.bsv $(BUILDDIR)/Prelude.bo $(BUILDDIR)/Prelude.bo
$(BUILDDIR)/Probe.bo:	Probe.bsv $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/ProbeWire.bo:	ProbeWire.bsv $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/RWire.bo:	RWire.bsv $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Real.bo:	Real.bs $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/RegFile.bo:	RegFile.bs $(BUILDDIR)/ConfigReg.bo $(BUILDDIR)/List.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Reserved.bo:	Reserved.bs $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/RevertingVirtualReg.bo:	RevertingVirtualReg.bs $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/SShow.bo:	SShow.bs $(BUILDDIR)/ListN.bo $(BUILDDIR)/Vector.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/SplitPorts.bo:	SplitPorts.bs $(BUILDDIR)/List.bo $(BUILDDIR)/Vector.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
$(BUILDDIR)/Vector.bo:	Vector.bs $(BUILDDIR)/List.bo $(BUILDDIR)/Array.bo $(BUILDDIR)/Prelude.bo $(BUILDDIR)/PreludeBSV.bo
