# for "make clean" to work everywhere

CONFDIR = $(realpath ../..)

KEEPFILES=ahb_bus.v  ahb_default.v  ahb_ram.v  amba_tb.v  ram_1024x32.v

DONTKEEPFILES=  amba_tb.vcd.dump simv amba_tb.log

include $(CONFDIR)/clean.mk
