# -------------------------

INSTALL_NAME = Verilog.Quartus

VERI_FILES = \
	BRAM1.v\
	BRAM1BE.v\
	BRAM1Load.v\
	BRAM1BELoad.v\
	BRAM2.v\
	BRAM2BE.v\
	BRAM2Load.v\
	BRAM2BELoad.v\

OTHER_FILES = \

VCD_TEST_MODS = \

include ../Verilog/common.mk

# -------------------------
