# for "make clean" to work everywhere

CONFDIR = $(realpath ../..)

DONTKEEPFILES = *.post-m4 simfiles bfiles vfiles incfiles \
		SplitIfNested.bs.expandif.atsexpand.expected \
		NoSplitIfNested.bs.expandif.atsexpand.expected

include $(CONFDIR)/clean.mk
