# !/bin/sh 
#
# Check ADD:
#   Load an ADD
#   Store the same ADD
#   Compare the two
# (done twice on a small - 0.add - and a medium - 1.add - ADD).
#
rm -f *.tmp*
echo "---------------------------------------------------------------------------"
echo "--------------------- TESTING Load ADD and Store ADD ----------------------"
echo "---------------------------------------------------------------------------"     
./../testdddmp << END1
mi
3
hlb
0.add
al
0.add
0
as
0.add.tmp
0
mq
mi
50
hlb
1.add
al
1.add
1
as
1.add.tmp
1
mq
quit
END1
echo "----------------------------- ... RESULTS ... -----------------------------"
diff --brief 0.add 0.add.tmp
diff --brief 1.add 1.add.tmp
echo "-------------------------------- ... END ----------------------------------"
rm -f *.*.tmp    
