# !/bin/sh 
#
# BDD check: 
#   Load BDDs
#   Make some operations
#   Store BDDs
#
rm -f *.*.tmp
echo "---------------------------------------------------------------------------"
echo "----------------------- TESTING basic Load/Store ... ----------------------"
echo "---------------------------------------------------------------------------"
./../testdddmp << END
mi
50
hlb
0or1.bdd
bl
0.bdd
0
bl
1.bdd
1
op
or
0
1
2
bs
0or1.bdd.tmp
2
bl
2.bdd
2
bl
3.bdd
3
op
and
2
3
4
bs
2and3.bdd.tmp
4
hlb
4xor5.bdd
bl
4.bdd
4
bl
5.bdd
5
op
xor
4
5
6
bs
4xor5.bdd.tmp
6
mq
quit
END
echo "----------------------------- ... RESULTS ... -----------------------------"
diff --brief 0or1.bdd 0or1.bdd.tmp
diff --brief 2and3.bdd 2and3.bdd.tmp
diff --brief 4xor5.bdd 4xor5.bdd.tmp
echo "-------------------------------- ... END ----------------------------------"
rm -f *.*.tmp
