# for "make clean" to work everywhere

CONFDIR = $(realpath ../..)

DONTKEEPFILES = \
	IncludeAbsolute.bsv.bsc-vcomp-out.expected \
	IncludeAbsolute.bsv \
	libdir1 libdir2

include $(CONFDIR)/clean.mk
