# for "make clean" to work everywhere

CONFDIR = $(realpath ../..)

DONTKEEPFILES = \
	defines bdir BdirVsSame_BdirOld.bsv BdirVsSame_BdirNew.bsv \
	libdir1 libdir2 \
	libdir3 libdir4

include $(CONFDIR)/clean.mk
