# for "make clean" to work everywhere

CONFDIR = $(realpath ../../..)

KEEPFILES += \
	mkPragmas_0_file.txt \
	mkPragmas_1_file.txt \
	mkPragmas_2_file.txt \
	mkPragmas_3_file.txt \

include $(CONFDIR)/clean.mk
