.PHONY: all clean full_clean

all:
	cd src && $(MAKE)
	cd HaskellIfc && $(MAKE)

clean:
	cd src && $(MAKE) clean
	cd HaskellIfc && $(MAKE) clean

full_clean:
	cd src && $(MAKE) distclean
	cd HaskellIfc && $(MAKE) full_clean
