{-# LANGUAGE CPP #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -Wall #-}

module Main_bo2bloogle (main) where

import CSyntax
import CType (isTConArrow, isTConPair)
import Control.Applicative (liftA2)
import Control.Category ((>>>))
import Control.Monad (forM_, void)
import Control.Monad.Except (ExceptT (..), MonadError (..), runExceptT)
import Control.Monad.IO.Class (MonadIO (..))
import Control.Monad.Reader (MonadReader (..), ReaderT, asks, runReaderT)
import Control.Monad.Trans (lift)
import Data.Bifunctor (Bifunctor (..))
import qualified Data.ByteString as BS
import Data.Char
  ( GeneralCategory (..),
    generalCategory,
    isLowerCase,
    isUpperCase,
  )
import Data.String (IsString (..))
import Error (initErrorHandle)
import GenBin (readBinFile)
import ISyntax (IPackage)
import Id (Id, getIdBaseString)
import PPrint (pp80)
import PreIds (idPrimUnit)
import System.Environment (getArgs)
import System.Exit (ExitCode (..), exitWith)
import System.IO (hPutStrLn, stderr)

main :: IO ()
main = do
  -- We require at least one path, because it's not particularly meaningful to
  -- make a Bloogle database from an empty package.
  (hooglePkgName, paths) <-
    getArgs >>= \case
      hooglePkgName : path : paths -> pure (hooglePkgName, path : paths)
      _ -> do
        mapM_
          (hPutStrLn stderr)
          [ "Usage: bo2bloogle PACKAGE-NAME PATHS...",
            "",
            "Outputs declarations Bloogle can read to stdout.",
            "",
            "Example:",
            "    # Build the Bloogle database",
            "    bo2bloogle foo $(find ~/src/foo -name '*.bo') > baz/foo.txt",
            "    bo2bloogle bar $(find ~/src/bar -name '*.bo') > baz/bar.txt",
            "    bloogle generate asdf.hoo baz",
            "",
            "    # Run a single Bloogle search",
            "    bloogle search asdf.hoo 'Fin 32 -> Vector n a -> a'",
            "",
            "    # Start the Bloogle server",
            "    bloogle server asdf.hoo"
          ]
        exitWith (ExitFailure 1)

  errh <- initErrorHandle
  putStrLn "-- Hoogle package file generated by bo2bloogle"
  putStrLn ("@package " <> hooglePkgName)
  putStrLn "@version 0"
  forM_ paths $ \path -> do
    contents <- BS.readFile path
    (CSignature pkgName _ _ defns, _, _ :: IPackage (), _) <-
      readBinFile errh path contents
    putStrLn ("\nmodule " ++ getIdBaseString pkgName)
    forM_ defns $ \defn -> do
      let ctx = "converting " <> whatIsDefn defn
      void $ runM 0 [] (catch 0 ctx $ printDefn defn)

-- | Hoogle takes as input (to @hoogle generate@) Haskell declarations that it
-- parses with the actual GHC parser. This class is for types that can possibly
-- be printed in Haskell syntax.
class AsHaskell a where
  -- | If a value can be printed as Haskell, returns the Haskell syntax for it
  -- (as a 'ShowS'). If not, returns 'notRepresentable'.
  asHS :: a -> M ShowS

toS :: String -> ShowS
toS s = (s <>)

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

intercalateS :: ShowS -> [ShowS] -> ShowS
intercalateS _ [] = id
intercalateS sep (hd : tl) = concatS (hd : ((sep .) <$> tl))

-- | This is the monad we convert to Haskell in.
newtype M a = MkM {unM :: ReaderT (Int, [String]) (ExceptT String IO) a}
  deriving (Functor, Applicative, Monad, MonadIO)

-- | Runs the 'M' monad.
runM :: Int -> [String] -> M a -> IO (Either String a)
runM indent ctx = runExceptT . flip runReaderT (indent, ctx) . unM

-- | Converts errors to comments on stdout.
catch :: Int -> String -> M () -> M ()
catch i ctxLine body = MkM . local (bimap (+ i) (ctxLine :)) $ do
  (i', ctx) <- ask
  result <- liftIO $ runM i' ctx body
  case result of
    Left err -> do
      unM $ printIndented (prefixed "-- " err)
    Right () -> pure ()

-- | Signals that the value is not representable as Haskell code.
notRepresentable :: String -> M a
notRepresentable msg = MkM $ do
  ctx <- asks (snd >>> fmap ("  while " <>))
  lift (throwError (unlines (msg : ctx)))

instance IsString (M ShowS) where
  fromString s = pure (s <>)

instance Semigroup (M ShowS) where
  (<>) = liftA2 (.)

instance Monoid (M ShowS) where
  mempty = pure id

-- | Adds parentheses.
parens :: M ShowS -> M ShowS
parens s = "(" <> s <> ")"

prefixed :: String -> String -> String
prefixed pfx = lines >>> fmap (pfx <>) >>> unlines

printIndented :: String -> M ()
printIndented str = do
  indent <- MkM $ asks (\(i, _) -> replicate (2 * i) ' ')
  liftIO $ putStr (prefixed indent str)

-- | Joins a sequence of words with a custom separator.
hsIntercalate :: String -> [M ShowS] -> M ShowS
hsIntercalate sep = sequence >>> fmap (intercalateS (toS sep))

-- | Joins a sequence of words.
hsUnwords :: [M ShowS] -> M ShowS
hsUnwords = hsIntercalate " "

-- | Builds a string up out of tuple-like syntax.
hsTuple :: [M ShowS] -> M ShowS
hsTuple =
  sequence
    >>> fmap (intercalateS (toS ", "))
    >>> parens

-- | Joins a sequence of words and prints them.
hsPrintWords :: [M ShowS] -> M ()
hsPrintWords ws = do
  str <- ($ []) <$> hsUnwords ws
  printIndented str

data Representable = Id | Sym

-- | Returns whether a name can be represented at all in Hoogle's Haskell
-- syntax. This essentially just checks if the string parses as @varid@,
-- @conid@, @varsym@, or @consym@ from the Haskell 2010 report.
checkRepresentable :: String -> Maybe Representable
checkRepresentable name
  | name `elem` reserved = Nothing
  | length name >= 2 && all (== '-') name = Nothing
  | isVarIdOrConIdOrReservedId name = Just Id
  | isVarSymOrConSymOrReservedOpOrDashes name = Just Sym
  | otherwise = Nothing
  where
    isSmallOrLarge :: Char -> Bool
    isSmallOrLarge ch = isLowerCase ch || isUpperCase ch || ch == '_'
    isDigit :: Char -> Bool
    isDigit ch = generalCategory ch == DecimalNumber
    -- Despite what the Haskell 2010 Report says, the 'otherwise' case is _not_
    -- 'isPunctuation ch || isSymbol ch'; GHC has its own split based on general
    -- category.
    isHsSymbol :: Char -> Bool
    isHsSymbol ch
      | ch `elem` ("(),;[]`{}_\"'" :: [Char]) = False
      | otherwise = generalCategory ch `elem` hsSymbolCategories
    hsSymbolCategories :: [GeneralCategory]
    hsSymbolCategories =
      [ ConnectorPunctuation,
        DashPunctuation,
        OtherPunctuation,
        MathSymbol,
        CurrencySymbol,
        ModifierSymbol,
        OtherSymbol
      ]

    isVarIdOrConIdOrReservedId :: String -> Bool
    isVarIdOrConIdOrReservedId [] = False
    isVarIdOrConIdOrReservedId (hd : tl) = isSmallOrLarge hd && all isIdRest tl
      where
        isIdRest :: Char -> Bool
        isIdRest ch = isSmallOrLarge ch || isDigit ch || ch == '\''
    isVarSymOrConSymOrReservedOpOrDashes :: String -> Bool
    isVarSymOrConSymOrReservedOpOrDashes [] = False
    isVarSymOrConSymOrReservedOpOrDashes s = all isHsSymbol s

    -- The list of strings that are @reservedid@ and @reservedop@.
    reserved :: [String]
    reserved =
      [ "case",
        "class",
        "data",
        "default",
        "deriving",
        "do",
        "else",
        "foreign",
        "if",
        "import",
        "in",
        "infix",
        "infixl",
        "infixr",
        "instance",
        "let",
        "module",
        "newtype",
        "of",
        "then",
        "type",
        "where",
        "_",
        "..",
        ":",
        "::",
        "=",
        "\\",
        "|",
        "<-",
        "->",
        "@",
        "~",
        "=>"
      ]

instance AsHaskell Id where
  asHS i =
    let name = getIdBaseString i
     in case checkRepresentable name of
          Just Id -> pure (toS name)
          Just Sym -> parens (pure (toS name))
          Nothing ->
            notRepresentable
              ( "the name "
                  <> show name
                  <> " is not valid in Haskell"
              )

instance AsHaskell IdK where
  asHS = iKName >>> asHS

instance AsHaskell CType where
  asHS (TVar i) = asHS i
  asHS (TCon c) = asHS c
  asHS ty@(TAp (TAp (TCon f@(TyCon {})) _) _)
    | isTConArrow f =
        let toSpineLoop :: [CType] -> CType -> [CType]
            toSpineLoop acc (TAp (TAp (TCon f') a) b)
              | isTConArrow f' = toSpineLoop (a : acc) b
            toSpineLoop acc t = reverse (t : acc)
         in parens (hsIntercalate " -> " (asHS <$> toSpineLoop [] ty))
    | isTConPair f =
        let toSpineLoop :: [CType] -> CType -> [CType]
            toSpineLoop acc (TAp (TAp (TCon f') a) b)
              | isTConPair f' = toSpineLoop (a : acc) b
            toSpineLoop acc t = reverse (t : acc)
         in parens (hsIntercalate ", " (asHS <$> toSpineLoop [] ty))
  asHS ty@(TAp _ _) =
    let toSpineLoop :: [CType] -> CType -> [CType]
        toSpineLoop acc (TAp f x) = toSpineLoop (x : acc) f
        toSpineLoop acc f = f : acc
     in parens (hsUnwords (asHS <$> toSpineLoop [] ty))
  asHS (TDefMonad _) =
    error "unreachable: (Bin Type) never produces TDefMonad"
  asHS (TGen _ n)
    | n < 0 = notRepresentable ("(TGen (" <> show n <> ")) had a negative index")
    | otherwise = pure (toS ("tGen_" <> show n))

instance AsHaskell CPred where
  asHS (CPred {cpred_tc = CTypeclass tc, cpred_args}) =
    hsUnwords (asHS tc : (asHS <$> cpred_args))

instance AsHaskell CQType where
  asHS (CQType [] ty) = asHS ty
  asHS (CQType provisos ty) =
    hsUnwords [hsTuple (asHS <$> provisos), "=>", asHS ty]

instance AsHaskell TyCon where
  asHS (TyCon {tcon_name})
    | tcon_name == idPrimUnit = "()"
    | otherwise = asHS tcon_name
  asHS (TyNum {tynum_value}) = pure (toS (show tynum_value))
  asHS (TyStr {tystr_value}) = pure (toS (show tystr_value))

instance AsHaskell TyVar where
  asHS (TyVar {tv_name}) = asHS tv_name

printDefn :: CDefn -> M ()
printDefn (Ctype ik args ty) =
  hsPrintWords (["type", asHS ik] <> (asHS <$> args) <> ["=", asHS ty])
printDefn (Cdata {cd_name, cd_type_vars}) =
  hsPrintWords (["data", asHS cd_name] <> (asHS <$> cd_type_vars))
printDefn (Cstruct _ _ ik args fields _) = do
  hsPrintWords (["data", asHS ik] <> (asHS <$> args))
  forM_ fields $ \(CField {cf_name, cf_type}) ->
    catch 0 ("converting " <> getIdBaseString cf_name) $ do
      -- TODO: This is the wrong syntax for field accessors, but we don't have a
      -- way to get the right syntax.
      hsPrintWords
        ( [asHS cf_name, "::", asHS ik]
            <> (asHS <$> args)
            <> ["->", asHS cf_type]
        )
printDefn (Cclass _ _ ik args _ tyFuns fields) = do
  hsPrintWords
    ( ["class", asHS ik]
        <> (asHS <$> args)
        <> ["where"]
    )
  forM_ tyFuns $ \(CAssocDepFun {ca_name, ca_params, ca_rhs}) ->
    catch 1 ("converting " <> getIdBaseString ca_name) $ do
      hsPrintWords
        ( ["type", asHS ca_name]
            <> (asHS <$> ca_params)
            <> ["=", asHS ca_rhs]
        )
  forM_ fields $ \(CField {cf_name, cf_type}) ->
    catch 1 ("converting " <> getIdBaseString cf_name) $ do
      hsPrintWords [asHS cf_name, "::", asHS cf_type]
printDefn (Cinstance {}) =
  error "unreachable: (Bin CDefn) never produces Cinstance"
printDefn (CValueSign {}) =
  error "unreachable: (Bin CDefn) never produces CValueSign"
printDefn (CValue {}) = error "unreachable: (Bin CDefn) never produces CValue"
printDefn (Cprimitive i ty) = hsPrintWords [asHS i, "::", asHS ty]
printDefn (CPragma _) = pure ()
printDefn (CprimType ik) = hsPrintWords ["data", asHS ik]
printDefn (Cforeign {cforg_name, cforg_type}) =
  hsPrintWords [asHS cforg_name, "::", asHS cforg_type]
printDefn (CIinstance _ qt) = hsPrintWords ["instance", asHS qt]
printDefn (CItype ik args _) =
  hsPrintWords (["data", asHS ik] <> (asHS <$> args))
printDefn (CIclass _ _ ik args _ tyFuns _) = do
  hsPrintWords
    ( ["class", asHS ik]
        <> (asHS <$> args)
        <> ["where"]
    )
  forM_ tyFuns $ \(CAssocDepFun {ca_name, ca_params, ca_rhs}) ->
    catch 1 ("converting " <> getIdBaseString ca_name) $ do
      hsPrintWords
        ( ["type", asHS ca_name]
            <> (asHS <$> ca_params)
            <> ["=", asHS ca_rhs]
        )
printDefn (CIValueSign i ty) = hsPrintWords [asHS i, "::", asHS ty]

whatIsDefn :: CDefn -> String
whatIsDefn (Ctype ik _ _) = "the type " <> getIdBaseString (iKName ik)
whatIsDefn (Cdata {cd_name}) = "the type " <> getIdBaseString (iKName cd_name)
whatIsDefn (Cstruct _ _ ik _ _ _) = "the type " <> getIdBaseString (iKName ik)
whatIsDefn (Cclass _ _ ik _ _ _ _) =
  "the class " <> getIdBaseString (iKName ik)
whatIsDefn (Cinstance {}) =
  error "unreachable: (Bin CDefn) never produces Cinstance"
whatIsDefn (CValueSign {}) =
  error "unreachable: (Bin CDefn) never produces CValueSign"
whatIsDefn (CValue {}) = error "unreachable: (Bin CDefn) never produces CValue"
whatIsDefn (Cprimitive i _) = "the value " <> getIdBaseString i
whatIsDefn (CPragma _) = "a pragma"
whatIsDefn (CprimType ik) = "the type " <> getIdBaseString (iKName ik)
whatIsDefn (Cforeign {cforg_name}) = "the value " <> getIdBaseString cforg_name
whatIsDefn (CIinstance _ qt) = "the instance " <> pp80 qt
whatIsDefn (CItype ik _ _) = "the type " <> getIdBaseString (iKName ik)
whatIsDefn (CIclass _ _ ik _ _ _ _) =
  "the class " <> getIdBaseString (iKName ik)
whatIsDefn (CIValueSign i _) = "the value " <> getIdBaseString i
