#!/bin/sh
# Regenerate Warmup.hs: an import of every exposed module of every
# dependency package, so that compiling Warmup first (every leaf module
# imports it) loads the entire external-package interface set -- and
# hence every imported rewrite rule and instance -- into GHC's EPS in
# one deterministic order, before any parallel compilation begins.
# Without this, `ghc --make -jN` object output varies from build to
# build with thread scheduling (rule visibility and rule-overlap order
# both depend on interface-load order; see GHC.Core.Rules,
# Note [Overall plumbing for rules], "[NB: we are inconsistent here...]").
#
# Usage: update-warmup.sh <ghc> <package>...
#        update-warmup.sh --list-extra <ghc>
# The matching ghc-pkg is derived from the ghc name/path.
# --list-extra prints the hidden rule-bearing packages present on this
# GHC (ghc-internal, ghc-bignum on >= 9.10), for the Makefile to expose.

if [ "$1" = "--list-extra" ] ; then
  LIST_EXTRA=1; shift
else
  LIST_EXTRA=0
fi

GHC_BIN="$1"; shift

case "$GHC_BIN" in
  */*) GHCPKG="$(dirname "$GHC_BIN")/ghc-pkg$(basename "$GHC_BIN" | sed 's/^ghc//')" ;;
  *)   GHCPKG="ghc-pkg$(printf '%s' "$GHC_BIN" | sed 's/^ghc//')" ;;
esac

if [ "$LIST_EXTRA" = 1 ] ; then
  for p in ghc-internal ghc-bignum ; do
    if "$GHCPKG" field "$p" name >/dev/null 2>&1 ; then
      printf '%s ' "$p"
    fi
  done
  echo
  exit 0
fi

OUT=Warmup.hs
# Per-process, so two concurrent runs cannot truncate or delete each
# other's temporary file.
TMP="$OUT.new.$$"

{
  echo "-- Generated by update-warmup.sh; do not edit."
  echo "-- See that script for what this module is for."
  echo "module Warmup where"
  for p in "$@" ; do
    "$GHCPKG" field "$p" exposed-modules 2>/dev/null
  done | tr ' \t' '\n\n' | grep -E "^[A-Z][A-Za-z0-9_.']*$" | sort -u | \
    sed 's/^/import /; s/$/ ()/'
} > "$TMP"

if cmp -s "$TMP" "$OUT" ; then
  rm -f "$TMP"
  echo "$OUT up-to-date"
else
  mv "$TMP" "$OUT"
  echo "$OUT updated"
fi
