# for "make clean" to work everywhere

CONFDIR = $(realpath ../../..)

KEEPFILES = MkGetPut_alt_rw.bsv  MkGetPut_non_alt_rw.bsv  MkGPFIFO.bsv  MkGPSizedFIFO.bsv MkGetPut.bsv MkGPFIFO_alt_rw.bsv  MkGPFIFO_non_alt_rw.bsv

include $(CONFDIR)/clean.mk
