Bluespec Compiler (BSC) Release Notes
=====================================
:website: https://github.com/B-Lang-org/bsc
:last-update-label!:
:nofooter:

2026.07 Release
---------------

PLEASE NOTE!  This release includes backward-incompatible changes!
But it also introduces significant new features and performance
improvements.

Incompatibilities: This release enables the `-aggressive-conditions`
and `-sched-conditions` flags by default, each of which can be
disabled by `-no-aggressive-conditions` and `-no-sched-conditions`
respectively.  Type inference for untyped let-statements has changed;
code that relied on this will need an explicit type signature now, but
if necessary, the `-let-gen` flag is available to revert to the
previous behavior.  There is a syntax change in the output of Bluetcl
commands that report port lists for a method, as there may now be
multiple ports (or no ports) for method arguments and results.

New features: Method arguments and results are no longer restricted to
a single port in the generated Verilog.  BSC can generate multiple
ports, based on the type; see `SplitPorts` in the Libraries Reference
Guide.  Feedback on this experimental feature is welcomed.  Another
exciting new feature is that type classes can now contain associated
type functions (ATF), that allow users to define their own type
constructors for accessing the dependent types of the class -- like
`SizeOf` for the `Bits` class.

Among many improvements in run time and memory usage, some
long-standing issues have been addressed in the elaboration of
vector/array selection (GitHub PR#1008) and loops (GitHub PR#919) and
in the scaling of large modules (GitHub PR#957).

Many further performance improvements and new features are in the
pipeline.  Your ongoing feedback is welcome, either in the Groups.io
mailing lists or at the GitHub repository.

Changes since release 2026.01:

Documentation
~~~~~~~~~~~~~

* Updates to `README.md`
  ** Add Fedora and Homebrew to the list of systems with packaged BSC
     (GitHub PR#971, PR#972)

* Updates to `INSTALL.md`
  ** Mention the third-party Terra repository as a source for the
     `ghc-strict-concurrency` dependency when building on Fedora
     (GitHub PR#941)
  ** Clarify the GHC versions tested by the CI matrix (GitHub PR#1003)
  ** Note that package managers for some systems may have GHC versions
     that are older than what is tested in the CI (GitHub PR#1012)

Compiler
~~~~~~~~

* Turn on `-aggressive-conditions` and `-sched-conditions` flags
  by default (GitHub PR#966)
  ** If this increases compile time (GitHub Issue#1056), they can be
     individually turned off by providing `-no-aggressive-conditions`
     and `-no-sched-conditions` respectively

* Stop generalizing untyped `let` statements by default (GitHub PR#902)
  ** This eliminates a common source of error and makes it easier to
     use functions like `split`
  ** Code that relied on this feature can be made to work by providing
     an explicit general type signature
  ** If necessary, the flag `-let-gen` can be used to revert to the
     old behavior

* New support for splitting method arguments and results into multiple
  ports according to the type -- e.g. separate ports for fields of a
  struct (GitHub Issue#714, PR#729, PR#932, PR#849, PR#959, PR#983, PR#1039)
  ** This introduces new type classes to `Prelude` and new libraries
     `SplitPorts` and `SplitVector`
  ** Documentation for this feature is in the Libraries Reference
     Guide, under `SplitPorts` (GitHub PR#1079)

* New support for associated type functions (ATF) -- allows users to
  define their own type constructors for computing the dependent types
  of a type class, like `SizeOf` for `Bits` (GitHub PR#888, PR#935,
  PR#962, PR#1032, PR#955)
  ** `SizeOf` is itself now cleanly re-implemented as an associated
     type function, which means it can be safely used in more contexts
     now, such as inside interface and struct fields
     (see, for example, PR#968)
  ** Type synonyms are expanded as needed to uncover ATFs, fixing
     long-standing bugs with `SizeOf` (GitHub Issue#311, Issue#890, PR#916)

* New warning `T0157` for unused imports (GitHub PR#847, PR#920, PR#947, PR#924)

* Improvements to stage dump flags (GitHub PR#859)
  ** Allow `-dall` to take a file argument
  ** Allow `%s` in file names to be replaced by the stage name
  ** Include headers and footers when dumping to files
  ** Use distinct names for all stages
  ** Only overwrite a file the first time the stage is dumped;
     subsequent dumps append to the existing file

* Performance improvements
  ** Improve proviso instance reduction (GitHub PR#893, PR#914,
     PR#903, PR#981, PR#1032)
  ** Eliminate double parsing (GitHub PR#859)
  ** Improve elaboration (GitHub PR#911, PR#917, PR#918, PR#982,
     PR#940, PR#1007, PR#919, PR#957, PR#955)
  ** Improve scheduling (GitHub PR#910, PR#912, PR#913)
  ** Improve Verilog code generation (GitHub PR#929, PR#957)
  ** Improve Bluesim code generation (GitHub PR#987)
  ** Improve binary file access (GitHub PR#936)
  ** Improve Haskell evaluation (GitHub PR#915)

* Fix memory consumption issue when printing `T0033` errors
  (GitHub Issue#894, PR#896)

* Improve heuristics for choosing names of generated signals
  (GitHub PR#939, PR#940, PR#957)

* Fix spurious `T0029` type check errors (GitHub PR#980)

* Detect when coherent instance matching depends on incoherent matches
  and warn or error as appropriate (GitHub PR#923)

* Improve evaluator optimization rules, to simplify more occurrences of
  pack applied to unpack (GitHub PR#926)

* Remove the obsolete `-cross-info` flag (GitHub PR#919, Issue#863)

* Internal clean-ups (GitHub PR#938, PR#962, PR#954, PR#919)

Libraries
~~~~~~~~~

* Use `$fatal` for `Assert` so that simulation exits with a failure
  code (GitHub Issue#296, PR#907)

* In the `FloatingPoint` library, fix `FloatToFixed` of a denormalized
  number (GitHub PR#933)

* Add `Functor` and `Applicative` type classes as superclasses of
  `Monad` (GitHub Issue#878, PR#883, PR#888, PR#952, PR#984)
  ** `return` is now an alias for `pure` and not a member of `Monad`

* Add `Foldable` and `Traversable` type class libraries (GitHub PR#953, PR#984)

* Add `TreeMap` library based on Okasaki style red-black trees
  (GitHub PR#931)

* Add an `Ord` instance for `String` comparison (GitHub PR#931)

* Add `Rep` associated type function for `Generic` (GitHub PR#908)

* Add `PrintType` library for constructing type-level string
  representations for types (GitHub PR#958)

* Add `fromChunks` (inverse of `toChunks`) to the `Vector` library
  (GitHub PR#885)

* Remove unnecessary provisos in the `ZBusUtil` library (GitHub PR#903)

* Obsolete the `*S` interfaces in the `CGetPut` and `BGetPut`
  libraries, which were a workaround for previously not being able to
  use `SizeOf` in interface methods (GitHub PR#968)

* Simplify `vMkRWire1` which is only intended to be used internally by
  BSC and remove `vMkUnsafeRWire1` which should not have been created
  (GitHub PR#897)

Bluetcl
~~~~~~~

* Change the output format for `module ports` and `submodule full`
  commands to allow for method arguments and results to be split into
  multiple ports (GitHub PR#849, PR#959)
  ** This is updated in the User Guide documentation

* New `sim isfatal` subcommand for querying whether the simulation
  terminated because of a call to `$fatal` (GitHub PR#907)
  ** This is updated in the User Guide documentation

Bluesim
~~~~~~~

* Better handling of `$fatal` (GitHub PR#907)
  ** New C API tracks whether simulated terminated because of a call to
     `$fatal` and simulation exits with a failure status

* Improve code generation to have stable orderings, not dependent on
  the creation time of identifiers during compilation (GitHub PR#987)

Verilog
~~~~~~~

* Use plain port syntax for `Inout` ports when possible (GitHub PR#1001)
  ** Remove the `basicinout.pl` script, which is now unneeded

* Fix Verilog output for operators `/` and `%` applied to complex
  expressions (GitHub PR#939, PR#940)

* Fix port connections for imported methods with multiplicity
  (GitHub PR#928, PR#959)

Utilities
~~~~~~~~~

* Clean up the example Bluetcl scripts (provided as is, with no
  guarantees) so that they can at least be run out of the box
  (GitHub PR#986)

Test Suite
~~~~~~~~~~

* Add top-level `GNUMakefile` targets for running the full test suite
  (GitHub PR#930)

* Fix a race in the parallel `Makefile` targets that would lead to
  the additional long tests not being run (GitHub PR#1006)

* Update the `sed` arguments in Bluetcl test functions (GitHub PR#897)

* Improve the facilities for running backend-agnostic tests with
  multiple tests, such as checking dump output (GitHub PR#992)

* Use the `dumpba` utility to check generated `.ba` files, as `dumpbo`
  is used for `.bo` files (GitHub PR#957)

* Make some tests less sensitive to `PreludeBSV` positions
  (GitHub PR#897)

* Fix bit rot in the MPEG4 long test (GitHub PR#995)

* Clean up tests to have more predictable behavior across different
  simulators or to be less sensitive to differences, to eventually
  support running the test suite with Verilator
  (GitHub PR#995, PR#990, PR#991, PR#993)
  ** Some tests will require additional support from BSC
     (GitHub Issue#989, PR#994)

* Start a new section of the test suite `README.md` for conventions
  and tips for writing tests (GitHub PR#990)

* Many new tests for new features and bug fixes

* Update to recognize `aarch64`, not just `arm64` (GitHub PR#973)

Internal
~~~~~~~~

* Updates to GitHub CI (continuous integration)
  ** Add CI for Intel-based MacOS 26 (GitHub PR#973)
  ** Add CI for Ubuntu 26.04 (GitHub PR#973)
  ** Add CI for Arm-based Ubuntu 24.04 and 26.04 (GitHub PR#973)
  ** Add testing with the new GHC 9.14 (GitHub PR#898)
  ** Remove testing with GHC 9.4 which is no longer recommended (GitHub PR#898)
  ** Update the testing for GHC 9.10 to the latest 9.10.3 (GitHub PR#898)
  ** Update the GHC HLS version to the latest 2.13.0.0 (GitHub PR898)
  ** Update GitHub actions to newer versions (GitHub PR#898)
  ** Use the `haskell/ghcup-setup` Action to install GHC/GHCup (GitHub PR#973)

For Developers
~~~~~~~~~~~~~~

* Fix `STP_STUB=1` build option (GitHub Issue#595, PR#973)

* When compiling with multiple parallel GHC jobs (specified by
  `GHCJOBS`) scale the maximum heap size with the number of jobs
  (GitHub PR#1019)

* Increase the default stack size for profiling builds (GitHub PR#957)

* Continue to support building with the older GHC 8.8.4 in the Ubuntu
  22.04 package manager (GitHub Issue#1011, Issue#963, PR#1015)

* Updates to `DEVELOP.md` introductory document
  ** Add more links to documentation (GitHub PR#895)
  ** Prominently mention the Haskell Language Server (HLS) files and
     refer to the CI for examples of HLS, running GHC interactively
     (GHCi), and installing dependencies (GitHub PR#979)

'''

2026.01 Release
---------------

This release brings a number of performance improvements and bug
fixes, including more principled support for type synonyms.  The
release also adds BH syntax support to Bluetcl.  A new dependency,
on the `strict-concurrency` package, has been added for building BSC.
Users of `Generics` may need to update a constructor name.

Changes since release 2025.07:

General
~~~~~~~

* Add a script to report the external Haskell packages used by GHC to
  compile the BSC binaries, indicating the version, license, and
  copyright information for each package (GitHub PR#876)

Compiler
~~~~~~~~

* Fix the `Makefile` check for submodules to support building from
  within a Git repo that is not the BSC repo (GitHub PR#874)

* Implement `LiberalTypeSynonyms`: Type synonyms are macros that can
  be partially applied, but in certain contexts that require a real
  type, the macro must be expanded and BSC will report a user error if
  not all arguments are applied at that point (GitHub Issue#221,
  PR#833)

* Error message improvements
  ** Include the name of the foreign function in error `T0012` when
     any of its types are not in `Bits` (GitHub PR#833)
  ** Report the expected and given number of arguments in error `T0013`
     when type synonyms are partially applied (GitHub PR#833)

* Performance improvements
  ** Avoid O(n^2) blowup in the Verilog backend on the number of
     foreign function calls (GitHub PR#832)
  ** Improve the performance of resource scheduling when the number of
     resource uses is large (GitHub PR#828)
  ** Improve the performance of writing large `.bi` files in the
     `writeBin` stage (GitHub PR#856)
  ** Improve time and memory usage during type check (GitHub PR#857)
  ** Improve time and memory usage during elaboration (GitHub PR#861,
     PR#858)
  ** Improve the performance of expression and type substitution
     during elaboration (GitHub PR#854)
  ** Improve typecheck and elaboration by not generating unnecessary
     bindings for provisos and by using sequential `let` instead of
     recursive, which also allows for future optimization (GitHub
     PR#848)
  ** Improve performance throughout the compiler by replacing the
     locally defined `Hyper` typeclass with the standard `NFData`
     Haskell library (GitHub PR#851)
  ** Replace old snapshot of `MVarStrict` (adjusted to use `Hyper`)
     with the standard `MVar.Strict` Haskell library (GitHub PR#852)
     *** This adds a dependency on the `strict-concurrency` package

* Bug fixes
  ** Eliminate an internal error in examples with numeric type
     constructors (GitHub Issue#309, PR#833, PR#844)
  ** Eliminate an internal error in examples where `SizeOf` still
     exists after elaboration (GitHub Issue#310, Issue#593, Issue#841,
     PR#842)
  ** For wire modules with zero-size variants, generate the value as a
     literal zero rather than don't-care, to avoid triggering
     eventual optimization bugs (GitHub Issue#836, PR#837)
  ** Fix a don't-care equality optimization in the evaluator that was
     incorrectly applying to zero-sized values (GitHub Issue#836,
     PR#837)
  ** Fix position-tracking in the BH/Classic parser that was off by
     one column after system task identifiers prefixed with `$`
     (GitHub PR#873, PR#875)

Libraries
~~~~~~~~~

* Add `lookupAll` utility to the `List` library (GitHub PR#845)

* Extend the `Generics` representation to include type constructors
  that take numeric and ordinary star kind arguments (GitHub PR#855)
  ** This is a breaking change that renames `ConArg` to `OtherConArg`

* Fix bug in `mkAlwaysFSM` for a sequence of one action
  (GitHub Issue#825, PR#826)

* Fix `oneHotSelect` in the `List` library to allow zero-width
  elements (GitHub Issue#839, PR#840)

* Remove unused `StmtFSMUtil` library (GitHub PR#827)

* Update build dependencies in `depends.mk` (GitHub PR#827)

Bluetcl
~~~~~~~

* Support BH/Classic (GitHub PR#838)
  ** New `syntax` command controls whether Bluetcl prints using BSV or
     BH syntax
  ** When parsing user input, Bluetcl first tries the chosen syntax,
     but will then try the other syntax if the first parse fails

Verilog
~~~~~~~

* Fix the Verilator link script to pass C linking information from the
  BSC command line to Verilator as `LDFLAGS` (GitHub PR#817)

Utilities
~~~~~~~~~

* In the template for compiling Bluesim as a stand-alone executable,
  fix a buffer overflow when writing a VCD (GitHub PR#821)

Test Suite
~~~~~~~~~~

* Update the Bluetcl test procedures to allow testing BSV and BH
  syntax, separately or together (GitHub PR#838)

Internal
~~~~~~~~

* Updates to GitHub CI (continuous integration)
  ** Generate the Haskell package information in BSC builds and
     include in the uploaded artifact (GitHub PR#876)
  ** Build and test in parallel using all available VM cores
     (GitHub PR#846, PR#870)
  ** Cancel in-progress workflows for a PR when new commits are pushed
     (GitHub PR#866)
  ** Support cross-repo development: When testing BSC builds in a
     branch of a fork (or in a PR), before cloning the `bsc-contrib`,
     `bdw`, or `Toooba` repos, check if a sibling fork exists with a
     branch of the same name and, if so, clone that version instead
     (GitHub PR#865, PR#867, PR#868)
  ** Retire the CI for MacOS 12 (GitHub PR#830)
  ** Add CI for Intel-based MacOS 15 (GitHub PR#830)
  ** Add CI for MacOS 26 (beta) (GitHub PR#830)
  ** Jobs not testing specific OS versions are bumped to Ubuntu 24.04
     and MacOS 15 (GitHub PR#830)
  ** Increase the timeout for building BSC on MacOS to allow for the
     slower run-time of Intel-based MacOS 15 runners (GitHub PR#835)
  ** Update GitHub actions to newer versions (GitHub PR#835)

For Developers
~~~~~~~~~~~~~~

* Support setting `BSCFLAGS` in the environment when building
  the libraries (GitHub PR#853)

* Add missing `trace-eq-witnesses` to the list of trace flags
  (GitHub PR#833)

* Improve the tracing of `ISyntax` expressions (GitHub PR#860)

'''

2025.07 Release
---------------

This release includes support for Tcl 9.0, enabling BSC to build on
Fedora Linux 42.  The release also improves the build instructions and
fixes a long-standing VPI issue with imported functions of no
arguments.

Changes since release 2025.01:

Documentation
~~~~~~~~~~~~~

* Clarify the `INSTALL.md` build instructions for BSC (GitHub PR#784)
  ** Adds instructions for building on Fedora Linux

* In the BH Reference Guide, clarify that the names for placeholder
  `inhigh` enable signals must be unique (GitHub PR#797)

* Fix the build status badge links in README.md
  (GitHub Issue#771, PR#773)

* Fix the build to fail if any of the documents fail to build
  (GitHub PR#799)

Compiler
~~~~~~~~

* Fix internal error on unknown type constructors in `match`
  assignment statements (GitHub Issue#785, PR#794)

* Fix the vendored STP library to build with GCC 15
  (GitHub Issue#786, PR#787)

Libraries
~~~~~~~~~

* In the `FloatingPoint` library, fix a bug in the
  `Rnd_Nearest_Away_Zero` rounding mode (round to nearest, ties away
  from zero) (GitHub PR#808)

Bluetcl
~~~~~~~

* Improve the foreign import of Tcl into Haskell (GitHub PR#801)
  ** Adds support for Tcl 9.0
  ** Helps with future support for Windows

Bluesim
~~~~~~~

* Silence an "unused result" warning when compiling designs
  containing the `Probe` module (GitHub PR#779)

* Silence variable-length array (VLA) warnings when compiling
  with Clang 17 and above, that would prevent compilation
  (GitHub Issue#812, PR#814)

Verilog
~~~~~~~

* Fix a bug in VPI code generation that would cause a runtime error
  for imported functions with no arguments, when using simulators such
  as Icarus Verilog (GitHub Issue#803, PR#804)
  ** Workarounds to add an unused argument are no longer needed

Utilities
~~~~~~~~~

* Updates to BSV mode for `emacs`
  ** Support `actionvalue`/`endactionvalue` blocks (GitHub PR#765)
  ** Highlight the `match` keyword (GitHub PR#766)

Test Suite
~~~~~~~~~~

* Add `check-suite-parallel` target to the top-level `GNUmakefile`
  (GitHub PR#805)

* Fix failing test due to warnings with newer GCC
  (GitHub Issue#800, PR#804)

Internal
~~~~~~~~

* Releases are now built with GHC 9.6.7 (previously 9.6.6)
  (GitHub PR#781)

* Updates to GitHub CI (continuous integration)
  ** Retire the CI for Ubuntu 20.04 (GitHub PR#781)
  ** Update the testing for GHC 9.6 to 9.6.7
     and for GHC 9.12 to 9.12.2 (GitHub PR#781)
  ** Update the GHC HLS version to the recommended 2.10.0.0
     (GitHub PR#781)
  ** Add an input to the build-and-test workflows to specify
     disabling timeouts, and use it to disable timeouts for
     macOS 13 (GitHub PR#815)
  ** Add an input to the macOS build-and-test workflow to
     specify disabling Homebrew updates, and use it to disable
     updates for macOS 13 (GitHub PR#815)

'''

2025.01.1 Release
-----------------

This release adds a comment about the new `Connectable` instance for
`ReadOnly` to `WriteOnly`.

2025.01 Release
---------------

This release fixes a four-year-old regression that, in rare cases,
would prevent a design from compiling.  The release also includes
the beginnings of new documentation for developers, with links to
information on the internals of BSC.

Changes since release 2024.07:

Documentation
~~~~~~~~~~~~~

* Fix the type of `truncate` in the Libraries Reference Guide
  (GitHub Issue#733, PR#734)

* Fix typo in the grammar rule for shorthands in ActionValue method
  definitions (GitHub PR#758)

* Fix issues with the documentation of numeric type operators in the
  BSC Libraries Guide (GitHub PR#759)

* Fix the Makefile dependencies for building the BSC Libraries Guide
  (GitHub PR#759)

Compiler
~~~~~~~~

* Fix a regression where designs would compile fine using BSC prior to
  October 2020, but would exceed unfolding steps using newer BSC, due
  to conditional expressions returning don't-care values for types
  with one constructor (GitHub Issue#742, PR#748)

* Fix the generation of signal names from real number constants,
  which could lead to illegal names containing decimal points or
  negative signs (GitHub PR#757)

Libraries
~~~~~~~~~

* Add `SShow` library, defining a typeclass analogous to `CShow`
  but for displaying values at compile time instead of run time
  (GitHub PR#724)

* Add `TStrCat` and `TNumToStr` operators for string types
  and `StrAlias` type class (GitHub PR#726)

* Export `mkUnsafeBypassWire` from `PreludeBSV` (GitHub PR#745)

* Add `isStaticValue` to `Prelude` (GitHub PR#747)

* Add `Connectable` instance for `ReadOnly` to `WriteOnly`
  (GitHub PR#756)

Test Suite
~~~~~~~~~~

* Support non-deterministic tests with multiple legal outputs, by
  adding a new `compare_file_list` procedure that takes a list of
  expected output files (GitHub PR#754)

* Support querying the macOS version in test scripts (GitHub PR#744)

* Support macOS 15, which has a slightly different CPP output for file
  paths (GitHub PR#744)

* Remove tests for the CUDD SAT solver which is no longer an option
  (GitHub PR#718)

Internal
~~~~~~~~

* Updates to GitHub CI (continuous integration)
  ** Retire the CI for macOS 12 (GitHub Issue#740, PR#744)
  ** Add CI for macOS 15 (GitHub PR#744)
  ** Add testing with the new GHC 9.12 (GitHub PR#754)
  ** Update the testing for GHC 9.8 to the latest 9.8.4 (GitHub PR#751)
  ** Update the GHC HLS version to the latest 2.9.0.1 (GitHub PR#751)
  ** Turn off `fail-fast` for matrix jobs that were missing this
     property (GitHub PR#757)
  ** Workaround an issue with GitHub's macOS runners where a conflict
     can occur if Homebrew attempts to install a new python package
     (GitHub PR#744)
  ** Workaround an issue with GitHub's macOS 14 runner, where the
     Homebrew `pyyaml` package is disabled, by installing in a python
     virual environment (GitHub PR#744)
  ** On macOS, install `texlive` instead of `mactex-no-gui` (PR#734)
     *** This saves disk space, runs faster, and works around an issue
         with GitHub's macOS 14 runner image

For Developers
~~~~~~~~~~~~~~

* Add an introductory document (`DEVELOP.md`) with information on the
  internal architecture of BSC and other helpful information for people
  who want to contribute to the source code (GitHub PR#752)

'''

2024.07 Release
---------------

Changes since release 2024.01:

Documentation
~~~~~~~~~~~~~

* Fix the type of `continuousAssert` in the Libraries Reference Guide
  (GitHub PR#686)

* Minor typo fix in the BH Reference Guide (GitHub PR#708)

Compiler
~~~~~~~~

* Update source code to compile with GHC 9.10.1 (GitHub PR#705)

Libraries
~~~~~~~~~

* Add BuildList library, analogous to BuildVector (GitHub PR#723)

Bluetcl
~~~~~~~

* Resolve a potential compilation warning by removing the use of
  K&R C syntax that is deprecated in newer C standards
  (GitHub PR#703)

Bluesim
~~~~~~~

* Add braces to some if-statements in generated {cpp} modules to avoid
  dangling-else warnings (GitHub Issue#442, PR#691)

* Resolve a warning during compilation of the Bluesim kernel by fixing
  a call to `bk_clock_name` in code that is unused except by
  developers for debugging (GitHub Issue#698, PR#702)

* Resolve a compilation error with newer {cpp} compilers by updating the
  source code to not use a feature that is deprecated since the C++20
  standard (GitHub Issue#698, PR#701)

Utilities
~~~~~~~~~

* Update BSV mode for `emacs` to work with newer versions
  (GitHub PR#697)

General
~~~~~~~

* Clean up how the `tcllibs` flags are computed in `platform.sh`
  (GitHub PR#703)
  ** This adds the version number to the flag for macOS
     (from `-ltcl` to `-ltcl8.5`)

Test Suite
~~~~~~~~~~

* Add support for querying the `MACHTYPE` so that tests can support
  different behavior on, say, `arm64` vs `x86_64`
  (GitHub Issue#688, PR#690)

Internal
~~~~~~~~

* Releases now built with GHC 9.6.6 (previously 9.4.8)
  (GitHub PR#705, PR#728)

* Updates to GitHub CI (continuous integration)
  ** Retire the CI for macOS 11 (GitHub PR#700)
  ** Add CI for macOS 14 (GitHub PR#690)
  ** Add CI for Ubuntu 24.04 (beta) (GitHub PR#700)
  ** Expand the number of GHC versions that are tested besides
     the version for releases -- previously only a single "latest"
     version was being tested (GitHub PR#705)
     *** Continue testing with older GHC 9.4.8,
         which GHCUP still labels as recommended
     *** Continue testing with GHC 9.8 (updated to the latest 9.8.2)
     *** Add testing with the new GHC 9.10.1
  ** Support leaving the `hls_version` field blank to indicate that
     the HLS testing step should be skipped (PR#703)
     *** This allows for testing newer GHC installations
         that don't yet have HLS support in GHCUP
  ** Ensure that `brew` and `apt-get` are updated before installing,
     to avoid failures due to old GitHub runner images (GitHub PR#687)

'''

2024.01 Release
---------------

Changes since release 2023.07:

Documentation
~~~~~~~~~~~~~

* Updates to the READMEs
  ** Add Gentoo to the list of OSes with BSC packages
  ** Update the URL for Icarus Verilog
  ** Additional links to documentation
  ** Link to Repology search for Bluespec packages

* Document string types in the BH and BSV Reference Guides

* Document the Generics feature and associated types and type class in
  the Libraries Reference Guide

* Minor cleanups and typo fixes in the BH and BSV Reference Guides and
  Libraries Reference Guide

Compiler
~~~~~~~~

* Fix a bug in scheduling inference for action methods with arguments,
  when an argument is used to conditionally execute an SBR action and
  inference doesn't otherwise determine the method to conflict with
  itself (GitHub issue #641)

* Change the derived `Generic` instance for enums and tagged unions
  to use a balanced binary tree
  ** This significantly improves the speed and memory use of the
     compiler on designs with large enums
     (GitHub issue #334, discussion #414)

* Remove the warning on uses of `Generic` that the feature is
  experimental, now that the implementation has settled

* Use UTF-8 instead of ISO-8859-1 for all text-like I/O (GitHub PR #601)
  ** Source files can now include non-Latin characters!

* In BH, disallow `°` and `´` in identifiers and instead parse them as symbols
  (GitHub PR #610)

* In BH, support more clock and reset pragmas available to BSV
  (GitHub issues #616, #224)
  ** Specifically: `gate_input_clocks`, `clock_family`, `clock_prefix`,
     `gate_prefix`, `reset_prefix`

* In BH, add missing features to the `properties` pragma (GitHub PR #626)

* In BH. fix the parsing of `arg_names` interface pragma to allow uppercase
  identifiers and disallow qualified names (GitHub issue #654)

* Fix the typecheck of struct update/literal/pattern (GitHub issue #628)
  ** This mostly fixes issues with qualified field names in BH,
     but may improve position information in error messages for BSV

* Fix the BSV parsing of naked expressions in statement and
  case-expression contexts (GitHub issue #646)

* Fix a failure to satisfy provisos during typecheck (GitHub issue #678)

* Update source code to compile with GHC 9.8

Libraries
~~~~~~~~~

* In BH, use the unicode ring operator (`∘`) for function composition
  (GitHub PR #601)

* Improve provisos in the `FixedPoint` package (GitHub PR #249)
  ** `FixedPoint` does not support an integer compoment with bit width
     less than one and this is now enforced with provisos
  ** The `epsilon` function also requires at least two bits in the
     representation
  ** Polymorphic uses of the `FixedPoint` type may need to add `Min`
     provisos (see GitHub PR #634 for example updates in the testsuite)

* Add a CShow generic instance for higher-rank fields

Bluetcl
~~~~~~~

* New `version ghc` subcommand for querying the version of GHC that
  the BSC tools were compiled with

Bluesim
~~~~~~~

* Fix the use of named sephamores, so that if Bluesim crashes before
  unlinking a semaphore, it won't cause a failure the next time Bluesim
  runs with the same process ID and attempts to link the same name
  (GitHub issue #611)

* Resolve `-Wformat-truncation` warning from GCC (GitHub PR #649)

Test Suite
~~~~~~~~~~

* When creating an archive of log files (`archive_logs.sh`),
  include the C++ compiler output for SystemC tests
  ** The GitHub CI uses this script to upload an artifact
     when there is a failure

* The GHC version used to build the BSC tools is available in the test
  infrastructure (as `$ghc_version`), for use when the expected
  behavior of a test differs depending on the GHC version

* Fix the value of `$bsc_version`

Internal
~~~~~~~~

* Releases now built with GHC 9.4.8 (previously 9.2.8)

* Updates to GitHub CI (continuous integration)
  ** Reorganization to support building and testing with a variety
     of GHC versions; for now, test with the version for release
     and with the latest version (9.8.1)
  ** Explicitly specify the Haskell Language Server (HLS) version to
     use, that is known to support the specified GHC version
  ** Turn off fast-fail, so that a failure for one OS version won't
     kill the processes testing other versions
  ** Support macOS VMs that don't have ghcup installed
  ** Support macOS VMs where the SystemC library is compiled with
     an unpredictable C++ standard

'''

2023.07 Release
---------------

Changes since release 2023.01:

Documentation
~~~~~~~~~~~~~

* Fix the syntax for struct patterns in the BSV Reference Guide

* Update the build instructions
  ** Document the `STP_STUB` and `YICES_STUB` options
  ** Clarify the options for testing

* Update the test suite README
  ** Add sections explaining the testing infrastructure and how to
     diagnose failures
  ** Document how to provide additional options to BSC
  ** Document how to specify the location and C++ options for SystemC

Compiler
~~~~~~~~

* Improvements to VPI wrapper locations for designs with imported C
  functions (import-BVI) that are compiled and linked for Verilog
  (GitHub discussion #575, PR #576)
  ** VPI wrappers are written to the same directory as the Verilog
     files in all cases; previously, they would be written to the
     current directory when the `-vdir` flag is not specified
  ** BSC linking will look for VPI wrappers in the `-vsearch` path;
     previously, BSC would look only in the `-vdir` directory if
     specified or the current directory if not

* Fix the parsing of `for` loop control in the `Stmt` sublanguage,
  to allow register assignment with array and field selection
  (GitHub issue #586)

* Source code cleanups
  ** Update to compile with GHC 9.6
  ** Resolve most incomplete pattern warnings, enabled in GHC 9.2
     (GitHub issue 469)

Libraries
~~~~~~~~~

* Lower the precedence of the `:=` operator in BH to match the
  precedence of `$` (GitHub discussion #567)

* Add a complex conjugate function (`cmplxConj`) to the `Complex`
  package

Verilog
~~~~~~~

* Update the Verilator link script
  ** Support version 5, which requires the `--no-timing` flag
  ** Remove the work directory when done, since it is not reused

* Update the Icarus Verilog link script to not generate `sft` files
  for newer versions (11+) as it is deprecated

Bluesim
~~~~~~~

* Remove uses of `sprintf` and replace with the safer `snprintf` or
  `asprintf`, to resolve warnings when building with some compilers
  (such as on macOS 13)

Utilities
~~~~~~~~~

* Improve indentation in the BSV mode for `vim`

General
~~~~~~~

* Replace deprecated `egrep` with `grep -E` as recommended by the
  POSIX standard, for greater portability

Test Suite
~~~~~~~~~~

* Update to pass with Icarus Verilog versions 12 and 13

* Add an option for specifying C++ flags to use with SystemC
  (`TEST_SYSTEMC_CXXFLAGS`)

* Update to invoke the C++ compiler in the same way that BSC does
    ** Use `c++` and not `g++`
    ** Use `CXXFLAGS` from the environment
       (but not yet `BSC_CXXFLAGS` as BSC does)

* Additional testing and small cleanups

Internal
~~~~~~~~

* Releases now built with GHC 9.2.8 (previously 9.0.2)

* Updates to GitHub CI (continuous integration)
  ** Retire the CI for Ubuntu 18.04 and macOS 10.15
  ** Add CI for macOS 13

'''

2023.01 Release
---------------

Changes since release 2022.01:

Documentation
~~~~~~~~~~~~~

* Addition of the BSV Language Reference Guide with updates

* Addition of the BH (Bluespec Haskell/Classic) Reference Guide with
  updates

* Fixes in the Libraries Reference Guide, for the `Cntrs`, `Clocks`,
  and `BRAMCore` libraries

Compiler
~~~~~~~~

* Fix to the pretty-printing of BH syntax for `letrec` and `letseq`

* Removed use of `-fpermissive` when compiling C/C++ files, which
  eliminates warnings when compiling with foreign imports

* For macOS 12 (XCode 14) and later, disabled chained fixups in the
  C++ compiler when generating shared objects, which resolves a
  warning about chained fixups not working with dynamic lookup

* Miscellaneous small optimizations

Libraries
~~~~~~~~~

* Fixes to the interface schedule for `mkSizedBypassFIFOF`
  (in `SpecialFIFOs`)

* Cleanup to `mkBRAMAdapter` (in `BRAM`)

* Addition of `getEvalPosition` to `Prelude`, which can be used
  similarly to `getStringPosition` to add position information to
  function error messages when a `String` argument is not available

Verilog
~~~~~~~

* Improved portability of Verilator linking by removing `bash`-isms
  from the shell script

Internal
~~~~~~~~

* Improvements to CI (continuous integration)

* Releases now built with GHC 9.0.2 (previously 9.0.1)

For Developers
~~~~~~~~~~~~~~

* Added support for using Haskell Language Server (HLS) on the BSC
  source code, via files provided in the `util` directory

'''

2022.01 Release
---------------

This release supports building and running on more systems, such as
CentOS 7.9, FreeBSD, Arm-based Macs, systems with Tcl 8.5, and macOS
when Tcl-Tk is installed via Homebrew.

This release also includes initial support for DPI instead of VPI (for
imported C functions) and support for automatic linking with Verilator
(using `-vsim verilator`).  Feedback on both of these features is
welcome!

Changes since release 2021.07:

General
~~~~~~~

* Update the install instructions
  ** Show how to use Bluetcl to programmatically retrieve the BSC version
  ** Show how to use Cabal `v2-install`
  ** Show how to build a release without Asciidoctor

* Support building and running on more systems

Documentation
~~~~~~~~~~~~~

* Fix typos in the `MIMO` library documentation

* Document new `-use-dpi` flag

* Document Verilator as a new option for `-vsim`

Compiler
~~~~~~~~

* Support optional use of DPI instead of VPI, for imported C functions (BDPI)
  ** This is draft support; feedback welcome!
  ** Size-polymorphic import-BDPI functions are not yet supported
  ** A new flag, `-use-dpi`, must be provided when compiling and linking

* Checkout the Yices submodule at an official tagged version, 2.6.4

* Udpate the source to compile with GHC 9.2
  ** Note that BSC triggers a bug in GHC 9.2.1 (#20639),
     which has been fixed in 9.2.2

Libraries
~~~~~~~~~

* Fix the modules in the `Divide` library
  ** Fix bug when iterations-per-cycle is greater than one
  ** Fix scheduling issues at the interface
  ** Improve the provisos

* Fix divide and square root modules in the `FloatingPoint` library,
  to not require `-aggressive-conditions` flag for correct behavior

* Fix `Prelude` function `hexDigitToInteger`

Bluesim
~~~~~~~

* Eliminate error on exit when running on systems with Tcl 8.5

Verilog
~~~~~~~

* Support automatic linking with Verilog, using `-vsim verilator`
  ** This is draft support; feedback welcome!
  ** The `-use-dpi` flag is needed for designs with imported C,
     since Verilator does not support our VPI implementation
  ** Designs with generated clocks may not link; ultimately, BSC may
     need a Verilator backend (separate from Verilog and Bluesim) to
     support arbitrary designs

'''

2021.07 Release
---------------

Welcome to the first release of open BSC!
Thank you and congratulations to everyone involved!

We have decided on the convention YYYY.MM for naming releases.
And we have decided on a release schedule of twice a year,
in January and July.  Therefore, this first release is 2021.07
and users can expect a next release, 2022.01, in six months.
Patch releases, if needed, will be named 2021.07.1, etc.

This release has some incompatibilities with prior proprietary
releases, but for the most part remains the same.  Hopefully
all projects using prior releases should find it accessible to
migrate to this open release.  But users should expect that
more incompatible changes may be coming in future releases.
Examples of changes to expect include:

* Renaming and reorganizing of directories in the release

* Renaming of Verilog primitives
  (for example, to start with a unique prefix such as `__BSC_`)

* Renaming of preprocessor macros
  (for example, changing the prefix `BSV_` to `BSC_`)

* New preprocessor macros
  (for example, rather than having Vivado-specific versions
  of Verilog primitives in a separate directory, they may
  coexist in one file and users may need to define a macro
  such as `VIVADO`, to select for the target tool)

* Use of newer Verilog features
  (rather than restricting primitives and generated Verilog to
  the Verilog95 standard as much as possible)

The changes in this release are highlighted below.
In addition, it is worth acknowledging the logistical and community
changes.  Most communication around open BSC happens on GitHub;
however, we also now have mailing lists, hosted at Groups.io.

* To receive announcements about BSC and related projects,
  subscribe to
  https://groups.io/g/b-lang-announce[b-lang-announce]

* For questions and discussion about BSC source,
  subscribe to the developers' mailing list
  https://groups.io/g/bsc-dev[bsc-dev]

* For any questions or discussion about Bluespec HDLs, using BSC,
  or related projects, subscribe to
  https://groups.io/g/b-lang-discuss[b-lang-discuss]

Only the core BSC tools have been included in the open BSC project
(compiler, standard libraries, Bluesim, and Bluetcl).  Some libraries
have been released in a separate GitHub repository,
https://github.com/B-Lang-org/bsc-contrib[`bsc-contrib`].
And BDW, the Bluespec Development Workstation GUI, has been released
as its own GitHub project,
https://github.com/B-Lang-org/bdw[`bdw`].
Other features from the proprietary release (such as BlueNoC, SCE-MI,
and other emulation tools and transactor libraries) have not been
released.

Highlights since proprietary release 2019.05:

Licensing
~~~~~~~~~

* FlexLM licensing has been removed from BSC and Bluesim, along with
  related flags

* Source is provided under the BSD-3-Clause license, except for some
  components where specified (under other open/copyleft licenses)

Documentation
~~~~~~~~~~~~~

* The documentation for standard libraries, that was previously found
  in the BSV Language Manual, has been collected into a stand-alone
  document, now residing in the `bsc` repo so that it can be updated
  as the libraries are updated

* BDW documentation has been removed from the User Guide and placed in
  its own document in the `bdw` repo; the remainder of the User Guide
  resides in the `bsc` repo where hopefully it can be updated
  as features are updated

General
~~~~~~~

* Users no longer need to set `BLUESPECDIR` -- the executables will
  expect the directory to sit at a known location relative to the
  executables

* The locations for C++ libraries (SAT, VPI, Bluesim) are no longer
  under a CXXFAMILY directory (for example, `g++4_64`)

* Version information no longer includes a date, just a build number
  (usually a git hash) and a version name (now reported as a single
  string instead of three separate fields)

Compiler
~~~~~~~~

* Removed unnecessary library requirements (X11, Tcl/Tk)
  ** Previously, the BSC executable required dynamic linking
     with Tcl, Tk, and X11 libraries -- which were legitimately
     needed for Bluetcl and Bluewish, but not for BSC

* Removed `Prelude` directory and consolidated all the libraries into
  the `Libraries` directory

* Flags and special support for BlueNoC/SCE-MI have been removed

* New flags `-show-timestamps` and `-show-version`

* New flag `-quiet` and its short form `-q`

* Yices is now the default SMT solver and the library is now included
  ** Support is updated to the latest version (2.6.2)
  ** Bugs have been fixed in BSC's use of Yices

* Support for CUDD solver removed, along with associated flags for
  scheduler effort and BDD cache size

* Better code generation for tagged unions and for enums that are
  non-consecutive or non-zero-based
  ** Pack-unpack of types results in pure wires in more cases
  ** More optimized code should occur in other situations, with fewer
     unnecessary case-statements

* Improved the handling of struct/union fields (in patterns,
  selection, and value construction)
  ** The BSV parser now accepts a pattern syntax for matching structs
  ** BSV syntax for struct vs tagged union can no longer be used
     interchangeably (users may need to add or remove the `tagged`
     keyword in existing code); this also means that clash between
     namespaces is no longer a problem
  ** BH/Classic still uses the same syntax for both structs and
     constructors with named fields, so the type checker still
     uses heuristics to decide which is intended -- this process
     has been improved
  ** Parsing/type-checking is now more strict about when named
     vs unnamed fields can be used
  ** Empty braces (without any listed fields) are disallowed in
     BSV syntax in situations where this does not make sense

* Record updates are now allowed on interfaces

* In BH/Classic, `prefix` is no longer a reserved keyword, and is now
  supported as an alternate to `prefixs` port renaming pragma

* Type-level strings are now supported, as a new string kind
  (alongside numeric and star kinds)
  ** The pseudo-function `stringOf` exists for converting a string
     type to a string value (along the lines of `valueOf` for
     numeric types)

* Fixed some `combsched` internal errors in scheduling

* Fixed an internal error on mutually recursive type class instances

* Fixed an issue where parallel calls to BSC would conflict if they
  used the C preprocessor, because it created a temporary file with a
  hard-coded name (fixed to use a unique name now)

* Fixed a bug in static evaluation of SLE/SLT on 0-width values

* Other efficiency improvements, error message improvements, and bug fixes
  ** Releases are also built with newer GHC versions, which ought to
     improve performance


Libraries
~~~~~~~~~

* Experimental support in the Prelude for datatype-generic functions,
  based on GHC's Generics:
  https://hackage.haskell.org/package/base/docs/GHC-Generics.html

* New `CShow` library (implemented with Generics), which provides a
  `CShow` typeclass that acts similar to `FShow` but prints values in
  BH/Classic syntax

* An instance of `FShow` is derived for `Either`

* The `DefaultValue` typeclass is now in `Prelude`, so it is
  automatically available and does not require importing a separate
  package

* The `guarded` parameter on FIFO primitives was fixed to be of type
  `Bool` rather than `Integer`

* Fix to `SquareRoot` library

Bluetcl
~~~~~~~

* The executable links with the locally installed Tcl/Tk and Itlk/Itk
  (rather than being compiled with source snapshots for specific
  versions) which also means that any locally installed Tcl libraries
  are available for use in Bluetcl

* The separate `bluewish` executable has been removed -- now that
  local libraries are used, Bluetcl users can `require` the local Tk
  package, to pull in Tk/X11 support

* Removed unnecessary library requirements (X11, Tk)
  ** Bluetcl can be run on systems where Tk/X11 is not available,
     as long as the Bluetcl commands don't request it

* `TCLLIBPATH` and `BLUETCLLIBPATH` environment variables are
  supported, for listing directories to add to the search path for
  packages

Bluesim
~~~~~~~

* Fixed code generation for conditionally called ActionValue
  methods/tasks

* Improved a scaling issue in Bluesim linking

* Handles `SIGPIPE` the same as Ctrl-C

Verilog
~~~~~~~

* Fixed typos in the Quartus versions of the Verilog primitives for
  BRAMs

* Fixed BSC linking for Icarus Verilog, so that the Verilog search
  path is also used for finding preprocessor include files

* BSC linking now supported for Questa (using `-vsim questa`)

* BSC linking for ModelSim updated to remove deprecated flag

'''
