#!/bin/sh

version=`egrep "^buildVersionName = " $1`

if [ $? -ne 0 ]
then
  echo "Failed to find version information in $1" > /dev/stderr
  exit 1
fi

str=`echo "$version" | cut -d\" -f2`

echo "static const char* version_name = \"$str\";"
