# for "make clean" to work everywhere

CONFDIR = $(realpath ../../..)

KEEPFILES = JoinServers1.bsv  MkRequestResponseBuffer_1.bsv  MkSizedRequestResponseBuffer.bsv JoinServers_twoserver.bsv  MkRequestResponseBuffer1.bsv   SplitServer1.bsv MkRequestBuffer.bsv  MkResponseBuffer.bsv

include $(CONFDIR)/clean.mk
