# for "make clean" to work everywhere

CONFDIR = $(realpath ../..)

# this is needed since cleanonly.mk keeps all files named testbench.v
DONTKEEPFILES = testbench.v random_testbench.v

include $(CONFDIR)/clean.mk
