## Bluespec Makefile for building tcl

DIRLIST = tcl8.5.4 tk8.5.4

.PHONY: all install clean full_clean
all: install

install:
	$(foreach dir, $(DIRLIST), \
		$(MAKE) -C $(dir) $@ ; )

clean full_clean:
	$(foreach dir, $(DIRLIST), \
		$(MAKE) -C $(dir) $@ ; )
