# for "make clean" to work everywhere

CONFDIR = $(realpath ../..)

KEEPFILES = mkBufferControl.bsv mkEntropyDec.bsv mkInputGen_akiyo224nodeblock.bsv  mkInputGen_news.bsv mkInterpolator_3stage.bsv mkMemED_bram.bsv mkPrediction_intra32.bsv mkCalc_nC.bsv mkEntropyDec_orig.bsv  mkInputGen_akiyo.bsv mkInputGen_nodeblock.bsv mkInterpolator_4stage_16ready.bsv mkMemED.bsv mkPrediction_intra8.bsv mkDeblockFilter.bsv mkFinalOutput.bsv mkInputGen.bsv mkInputGen_park20inter.bsv mkInterpolator_4stage.bsv mkMemED_regfile.bsv  mkTH.bsv mkDeblockFilter_dummy.bsv mkFrameBuffer.bsv mkInputGen_intersquid.bsv mkInputGen_park.bsv mkInterpolator.bsv mkNalUnwrap.bsv mkDeblockFilter_orig.bsv mkH264.bsv mkInputGen_intra.bsv mkInputGen_x264.bsv mkInverseTrans.bsv mkPrediction.bsv

include $(CONFDIR)/clean.mk
